#!/usr/bin/python3.6
#coding: utf-8

PKT_TYPE_0_CONN_INFO = 0
PKT_TYPE_1_CONN_STAT_REPORT = 1
PKT_TYPE_2_STREAM_DATA = 2
PKT_TYPE_3_ACK = 3
PKT_TYPE_4_REQUEST_PKT = 4
PKT_TYPE_5_ASSERTION = 5

ACK = 0
UNA = 1

CONN_STATUS_0_NO_CONN = 0
CONN_STATUS_1_CONNECTING = 1
CONN_STATUS_2_CONNECTED = 2
CONN_STATUS_3_DISCONNECTED = 3

ASSERTION_PASSIVE_DISCONNECTING = 0

CTRL_TYPE_0_SIG_DESTROY_HANDLER = 0
